name: build

on:
  push:

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        features: ["", "--no-default-features --features engine-lua54,engine-quickjs"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: lint
        run: just lint "${{ matrix.features }}"
      - name: build
        run: just build "${{ matrix.features }}"
      - name: test
        run: just test "${{ matrix.features }}"
